# Generated by Django 3.0.6 on 2020-11-03 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_latestpost_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestpost',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayımlanma Tarihi'),
        ),
    ]
