# Generated by Django 3.1.5 on 2021-01-25 10:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20201104_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Programming'), (2, 'Technology'), (3, 'International'), (5, 'IT')], max_length=30, null=True),
        ),
    ]
