# Generated by Django 3.1.5 on 2021-01-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210125_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MEOCHANNEL',
        ),
    ]
